server:
  port: 9090

spring:
  profiles:
    active: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always


logging:
  level:
    ru:
      practicum: DEBUG
    org:
      springframework:
        orm:
          jpa: INFO
        transaction:
          interceptor: TRACE
          JpaTransactionManager: DEBUG